added self.is_mounted=False To Nfs Classes
self.is_mounted=False to NfsGoldenImage and NfsStagingImage because it makes no sense for Nfs Images and its checked on the image_manager:

 # Checks if image is really mounted as per is_mounted = True
            if image.is_mounted:
                if not os.path.ismount(image.MOUNT_DIRECTORY):
                    image.is_mounted = False
                    image.register_image()

Causing the following Error:

[-] No nfs staging images. Golden image creation require an nfs staging image.
 1 - Generate a new nfs staging image
 2 - Generate a new nfs golden image from a staging image
 3 - Manage nodes of a golden image
-->: 2
ERROR:root:'NfsStagingImage' object has no attribute 'is_mounted'

[-] No nfs staging images. Golden image creation require an nfs staging image.
 1 - Generate a new nfs staging image
 2 - Generate a new nfs golden image from a staging image
 3 - Manage nodes of a golden image